# Generated by Django 5.0.3 on 2024-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('idbanco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombanco', models.CharField(blank=True, max_length=255, null=True)),
                ('codbanco', models.CharField(blank=True, max_length=255, null=True)),
                ('codach', models.CharField(blank=True, max_length=255, null=True)),
                ('digchequeo', models.CharField(blank=True, max_length=255, null=True)),
                ('nitbanco', models.CharField(blank=True, max_length=255, null=True)),
                ('tamcorriente', models.CharField(blank=True, max_length=255, null=True)),
                ('tamahorro', models.CharField(blank=True, max_length=255, null=True)),
                ('oficina', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('idcargo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(max_length=50)),
                ('nombrenivel', models.CharField(blank=True, max_length=50, null=True)),
                ('cargojefe', models.CharField(blank=True, max_length=50, null=True)),
                ('cargosacargo', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idciudad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, db_collation='es_ES', max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, db_collation='es_ES', max_length=50, null=True)),
                ('codciudad', models.CharField(blank=True, max_length=10, null=True)),
                ('coddepartamento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidadessegsocial',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=12)),
                ('entidad', models.CharField(max_length=120)),
                ('tipoentidad', models.CharField(max_length=20)),
                ('codsgp', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'entidadessegsocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('idpais', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'paises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('idprofesion', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'db_table': 'profesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodenomina',
            fields=[
                ('idtiponomina', models.IntegerField(primary_key=True, serialize=False)),
                ('tipodenomina', models.CharField(max_length=255)),
                ('cod_dian', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipodenomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id_tipo_doc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_dian', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposalario',
            fields=[
                ('idtiposalario', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tiposalario', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tiposalario',
                'managed': False,
            },
        ),
    ]
