# Generated by Django 5.0.4 on 2024-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_bancos_cargos_ciudades_entidadessegsocial_paises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptosdenomina',
            fields=[
                ('nombreconcepto', models.CharField(max_length=30)),
                ('multiplicadorconcepto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipoconcepto', models.IntegerField()),
                ('sueldobasico', models.IntegerField(blank=True, null=True)),
                ('auxtransporte', models.IntegerField(blank=True, null=True)),
                ('baseprestacionsocial', models.IntegerField(blank=True, null=True)),
                ('ingresotributario', models.IntegerField(blank=True, null=True)),
                ('prestacionsocial', models.IntegerField(blank=True, null=True)),
                ('extras', models.IntegerField(blank=True, null=True)),
                ('basesegsocial', models.IntegerField(blank=True, null=True)),
                ('cuentacontable', models.CharField(blank=True, max_length=25, null=True)),
                ('idconcepto', models.IntegerField(primary_key=True, serialize=False)),
                ('ausencia', models.IntegerField(blank=True, null=True)),
                ('salintegral', models.IntegerField(blank=True, null=True)),
                ('basevacaciones', models.IntegerField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, max_length=1, null=True)),
                ('basetransporte', models.SmallIntegerField(blank=True, null=True)),
                ('aportess', models.SmallIntegerField(blank=True, null=True)),
                ('incapacidad', models.SmallIntegerField(blank=True, null=True)),
                ('base1393', models.SmallIntegerField(blank=True, null=True)),
                ('norenta', models.SmallIntegerField(blank=True, null=True)),
                ('pension', models.SmallIntegerField(blank=True, null=True)),
                ('exentos', models.SmallIntegerField(blank=True, null=True)),
                ('baserarl', models.SmallIntegerField(blank=True, null=True)),
                ('basecaja', models.SmallIntegerField(blank=True, null=True)),
                ('viaticos', models.SmallIntegerField(blank=True, null=True)),
                ('comisiones', models.SmallIntegerField(blank=True, null=True)),
                ('gastosderep', models.SmallIntegerField(blank=True, null=True)),
                ('suspcontrato', models.SmallIntegerField(blank=True, null=True)),
                ('grupo_dian', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conceptosdenomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contabgrupos',
            fields=[
                ('idgrupo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('grupocontable', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'contabgrupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crearnomina',
            fields=[
                ('nombrenomina', models.CharField(blank=True, max_length=40, null=True)),
                ('fechainicial', models.DateField(blank=True, null=True)),
                ('fechafinal', models.DateField(blank=True, null=True)),
                ('fechapago', models.DateField(blank=True, null=True)),
                ('tipodenomina', models.CharField(blank=True, max_length=2, null=True)),
                ('mesacumular', models.CharField(blank=True, max_length=20, null=True)),
                ('anoacumular', models.CharField(blank=True, max_length=4, null=True)),
                ('estadonomina', models.SmallIntegerField(blank=True, null=True)),
                ('diasnomina', models.SmallIntegerField(blank=True, null=True)),
                ('idnomina', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'crearnomina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('idregistronom', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreconcepto', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('mesacumular', models.CharField(blank=True, max_length=15, null=True)),
                ('anoacumular', models.CharField(blank=True, max_length=15, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('estadonomina', models.SmallIntegerField(blank=True, null=True)),
                ('control', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nomina',
                'managed': False,
            },
        ),
    ]
