# Generated by Django 5.0.4 on 2024-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_conceptosdenomina_contabgrupos_crearnomina_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('idliquidacion', models.IntegerField(primary_key=True, serialize=False)),
                ('docidentidad', models.CharField(blank=True, max_length=15, null=True)),
                ('diastrabajados', models.CharField(blank=True, max_length=8, null=True)),
                ('cesantias', models.CharField(blank=True, max_length=30, null=True)),
                ('prima', models.CharField(blank=True, max_length=30, null=True)),
                ('vacaciones', models.CharField(blank=True, max_length=30, null=True)),
                ('intereses', models.CharField(blank=True, max_length=30, null=True)),
                ('totalliq', models.CharField(blank=True, max_length=30, null=True)),
                ('diascesantias', models.CharField(blank=True, max_length=8, null=True)),
                ('diasprimas', models.CharField(blank=True, max_length=8, null=True)),
                ('diasvacaciones', models.CharField(blank=True, max_length=8, null=True)),
                ('baseprima', models.CharField(blank=True, max_length=30, null=True)),
                ('basecesantias', models.CharField(blank=True, max_length=30, null=True)),
                ('basevacaciones', models.CharField(blank=True, max_length=30, null=True)),
                ('fechainiciocontrato', models.DateField(blank=True, null=True)),
                ('fechafincontrato', models.DateField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('motivoretiro', models.CharField(blank=True, null=True)),
                ('estadoliquidacion', models.CharField(blank=True, null=True)),
                ('diassusp', models.SmallIntegerField(blank=True, null=True)),
                ('indemnizacion', models.IntegerField(blank=True, null=True)),
                ('diassuspv', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'liquidacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMasivo',
            fields=[
                ('idliquidacion', models.IntegerField(primary_key=True, serialize=False)),
                ('docidentidad', models.CharField(blank=True, max_length=15, null=True)),
                ('diastrabajados', models.CharField(blank=True, max_length=8, null=True)),
                ('cesantias', models.CharField(blank=True, max_length=30, null=True)),
                ('prima', models.CharField(blank=True, max_length=30, null=True)),
                ('vacaciones', models.CharField(blank=True, max_length=30, null=True)),
                ('intereses', models.CharField(blank=True, max_length=30, null=True)),
                ('totalliq', models.CharField(blank=True, max_length=30, null=True)),
                ('diascesantias', models.CharField(blank=True, max_length=8, null=True)),
                ('diasprimas', models.CharField(blank=True, max_length=8, null=True)),
                ('diasvacaciones', models.CharField(blank=True, max_length=8, null=True)),
                ('baseprima', models.CharField(blank=True, max_length=30, null=True)),
                ('basecesantias', models.CharField(blank=True, max_length=30, null=True)),
                ('basevacaciones', models.CharField(blank=True, max_length=30, null=True)),
                ('idcontrato', models.IntegerField()),
                ('idempleado', models.IntegerField(blank=True, null=True)),
                ('fechainiciocontrato', models.DateField(blank=True, null=True)),
                ('fechafincontrato', models.DateField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('motivoretiro', models.CharField(blank=True, null=True)),
                ('estadoliquidacion', models.CharField(blank=True, null=True)),
                ('diassusp', models.SmallIntegerField(blank=True, null=True)),
                ('indemnizacion', models.IntegerField(blank=True, null=True)),
                ('diassuspv', models.CharField(blank=True, max_length=16, null=True)),
                ('idcosto', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'liquidacion_masivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NominaComprobantes',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('idcontrato', models.IntegerField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('idcosto', models.SmallIntegerField(blank=True, null=True)),
                ('pension', models.CharField(blank=True, max_length=125, null=True)),
                ('salud', models.CharField(blank=True, max_length=125, null=True)),
                ('idnomina', models.IntegerField(blank=True, null=True)),
                ('envio_email', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nomina_comprobantes',
                'managed': False,
            },
        ),
    ]
