# Generated by Django 5.0.7 on 2026-04-25 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre identificador (ej: talent-hcm-dev)', max_length=100)),
                ('url_destino', models.URLField(help_text='URL de HCM que recibe el webhook. Ej: https://hcm.summa.co/api/v1/webhooks/receive/')),
                ('api_key_destino', models.CharField(help_text='API Key para autenticar el POST a HCM', max_length=200)),
                ('eventos', models.JSONField(default=list, help_text='Lista de eventos a notificar. Ej: ["employee.created", "contract.updated"]')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suscripción Webhook',
                'verbose_name_plural': 'Suscripciones Webhook',
                'db_table': 'api_webhook_subscription',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Enviado'), ('failed', 'Fallido'), ('retrying', 'Reintentando')], default='pending', max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('intentos', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.webhooksubscription')),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Logs Webhook',
                'db_table': 'api_webhook_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
