# Generated by Django 5.0.4 on 2024-05-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_token_alter_empresa_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='login_empresa',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='login_usuario',
        ),
    ]
