# Generated by Django 5.0.4 on 2024-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=20)),
                ('role_label', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rolechoices',
                'managed': False,
            },
        ),
    ]
