# Generated by Django 5.0.4 on 2024-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrotrabajo',
            fields=[
                ('nombrecentrotrabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('tarifaarl', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('centrotrabajo', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'centrotrabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idciudad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(blank=True, db_collation='es_ES', max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, db_collation='es_ES', max_length=50, null=True)),
                ('codciudad', models.CharField(blank=True, max_length=10, null=True)),
                ('coddepartamento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('nomcosto', models.CharField(blank=True, max_length=30, null=True)),
                ('idcosto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('grupocontable', models.CharField(blank=True, max_length=4, null=True)),
                ('suficosto', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'costos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpVacaciones',
            fields=[
                ('id_sol_vac', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicialvac', models.DateField(blank=True, null=True)),
                ('fechafinalvac', models.DateField(blank=True, null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
                ('diasvac', models.SmallIntegerField(blank=True, null=True)),
                ('cuentasabados', models.SmallIntegerField(blank=True, null=True)),
                ('diascalendario', models.SmallIntegerField(blank=True, null=True)),
                ('ip_usuario', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios2', models.CharField(blank=True, max_length=255, null=True)),
                ('update_ip', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'emp_vacaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelosContratos',
            fields=[
                ('idmodelo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombremodelo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipocontrato', models.CharField(blank=True, max_length=255, null=True)),
                ('textocontrato', models.CharField(blank=True, max_length=10485760, null=True)),
                ('estadomodelo', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modelos_contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('nombresede', models.CharField(blank=True, max_length=40, null=True)),
                ('cajacompensacion', models.CharField(blank=True, max_length=60, null=True)),
                ('idsede', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('codccf', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'sedes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcostos',
            fields=[
                ('nomsubcosto', models.CharField(blank=True, max_length=30, null=True)),
                ('nomcosto', models.CharField(blank=True, max_length=30, null=True)),
                ('idsubcosto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('idcosto', models.SmallIntegerField(blank=True, null=True)),
                ('sufisubcosto', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'subcostos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoavacaus',
            fields=[
                ('tipovac', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombrevacaus', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipoavacaus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposalario',
            fields=[
                ('idtiposalario', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tiposalario', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tiposalario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('fechainicialvac', models.DateField(blank=True, null=True)),
                ('ultimodiavac', models.DateField(blank=True, null=True)),
                ('diascalendario', models.SmallIntegerField(blank=True, null=True)),
                ('diasvac', models.SmallIntegerField(blank=True, null=True)),
                ('diaspendientes', models.SmallIntegerField(blank=True, null=True)),
                ('idvacaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('pagovac', models.IntegerField(blank=True, null=True)),
                ('totaldiastomados', models.SmallIntegerField(blank=True, null=True)),
                ('basepago', models.IntegerField(blank=True, null=True)),
                ('estadovac', models.SmallIntegerField(blank=True, null=True)),
                ('idnomina', models.IntegerField(blank=True, null=True)),
                ('cuentasabados', models.SmallIntegerField(blank=True, null=True)),
                ('idvacmaster', models.IntegerField(blank=True, null=True)),
                ('perinicio', models.DateField(blank=True, null=True)),
                ('perfinal', models.DateField(blank=True, null=True)),
                ('fechapago', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacaciones',
                'managed': False,
            },
        ),
    ]
